### ISSUE TITLE
CI Bug: stwo exclusive programs are not compared with cairo-lang.

### ISSUE THREAD

**Issue by JulianGCalderon** [lambdaclass/cairo-vm#2061]
The QA workflow has the following matrix configuration for the `run-cairo-release` job:

```yaml
- program-target: cairo_stwo_exclusive_programs
  programs-dir: cairo_programs/stwo_exclusive_programs
  extra-args: '--cairo_pie_output {program}.rs.pie.zip'
- program-target: cairo_stwo_exclusive_programs_proof_mode
  programs-dir: cairo_programs/stwo_exclusive_programs
  extra-args: '--proof_mode --air_public_input {program}.rs.air_public_input --air_private_input {program}.rs.air_private_input '
```

This fails because there is no makefile recipe for either:

- cairo_stwo_exclusive_programs
- cairo_stwo_exclusive_programs_proof_mode

Which implies that there are is cache with that name either. Those programs are already generated by the `cairo_proof_programs` recipe.

As fetching that cache fails, then it means that we not actually executing the Cairo VM with stwo exclusive programs. We should fix it, or consider removing it entirely (as currently it does nothing).

links:
- https://github.com/lambdaclass/cairo-vm/actions/runs/14316883762/job/40125098264#annotation:5:587
- https://github.com/lambdaclass/cairo-vm/actions/runs/14316883762/job/40125097279#annotation:5:587
